{{- if .Values.RBAC.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.RBAC.clusterRoleName }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
  {{- with .Values.RBAC.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
{{- end }}
