{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "port-scan-exporter.fullname" . }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
spec:
  ingress:
    - ports:
      - port: {{ .Values.service.port }}
  egress:
  - {}
  policyTypes:
    - Egress
    - Ingress
  podSelector:
    matchLabels:
      {{- include "port-scan-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
