{{- if .Values.RBAC.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.RBAC.serviceAccountName }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
  {{- with .Values.RBAC.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
