config:
  listen_address: ":8080"
  portscan_timeout_ms: 150
  max_port: 65535
  rescan_interval_minutes: 10
  portscan_workers: 10
  expire_after_minutes: 720

rbac:
  create: true
  podSecurityPolicy:
    enabled: true

monitor:
  enabled: true
  interval: "15s"
  scrapeTimeout: 300s
