{
 "title": "Open ports dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ps_namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(portscan_open_ports,portscan_namespace)"
    }
   },
   {
    "name": "ps_pod",
    "label": "pod",
    "query": {
     "query": "label_values(portscan_open_ports{portscan_namespace=~\"$ps_namespace\"},portscan_pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Open TCP ports",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "portscan_open_ports{portscan_pod=~\"$ps_pod\", portscan_namespace=~\"$ps_namespace\"}"
    }
   ]
  },
  {
   "title": "Last port scan times",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "portscan_last_scan_time{portscan_namespace=~\"$ps_namespace\", portscan_pod=~\"$ps_pod\"}"
    }
   ]
  },
  {
   "title": "Last scan duration (ms)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "portscan_last_scan_duration{portscan_namespace=~\"$ps_namespace\",portscan_pod=~\"$ps_pod\"}"
    }
   ]
  }
 ]
}